fastify/fastify-nextjs

- .travis.yml
- package.json
- test.js
This is an attempt to solve failing test in #35
https://github.com/fastify/fastify-react/blob/ba3e4c7d69f5150a63ea5bb49680e6022a3651bd/test.js#L193
fails because `next@7` updated webpack from `3.x` to `4.x` which changed the generated next.js assets and their path too.
Since ef27bd9e6285638f06d2d77b7670affdf5e999b5 the plugin serves those assets with a wildcard route `/_next/*`. So the update doesn't affect the functionality and the plugin works with both `next@6` and `next@7` versions.
But running test against 2 different version of the same package feels messy (and I have no idea how to do it) that is why I simply change the test to use the new asset map. 
If you have a better approach in mind, please point to the direction, and I happy to adjust the PR. 
Edit:
`next@7` requires node …
> Fix broken test with next@7

- package.json
This PR is for working NODE_ENV in windows system
`'NODE_ENV' is not recognized as an internal or external command, operable program or batch file.`
> using cross-env for working NODE_ENV in windows

- index.js
I noticed fastify was complaining about empty requests and non-204 codes. This patch tells fastify a response was actually sent.
> Tell fastify a response was sent.

- README.md
- index.js
- package.json
Once name of the repo is changed we should verify travis and greenkeeper.
I also don't have permission to rename the repo so one of the core maintainers need to do it
> Replace fastify-react with fastify-nextjs

- .gitignore
- .travis.yml
- index.d.ts
- index.js
- package.json
- tsconfig.json
- types.test.ts
Next.js 9 ships its own types now.
They are not like the @types/next type defs so somethings need to change
I believe I was able to get the right type for DevServer, except now theres an error calling `handleRequest` 
```
types.test.ts:8:20 - error TS2341: Property 'handleRequest' is private and only accessible within class 'Server'.
```
Someone who understands next.js should figure out what change needs to be made here in the test and we can go from there
> update packages for next.js v9 types

- index.d.ts
- types.test.ts
This is only type definition fix. According to the documentation fastify.next('/hello') the 2nd and 3rd parameters are not required.
> Fixed typedefinition

- index.d.ts
- index.js
- pages/api/user.js
- test.js
- Use requestHandler of next-server as the default handler
- Remove the opts.next check
Closes #58 #89
> Use requestHandler of next-server as the default handler

- .gitignore
- index.js
- package-lock.json
- test.js
- types.test.ts
As it is right now, it is impossible to customize the logging level of the Next.js routes, even though the plugin type definitions have autoComplete for `logLevel`, and this PR reuses the plugin options `logLevel` config.
The test added fails if the changes in `index.js` are reverted.
> plugin logLevel

- index.js
- test.js
Fixes #84 (mostly).
Since Fastify buffers headers internally instead of setting them directly on the raw response, headers set by a plugin or hook using `reply.header()` or `reply.headers()` were discarded after control was passed to Next.js, since Next can only see the headers on the raw response and calls `.end()` directly on the response rather than letting Fastify serve it.
This fixes that issue by explicitly setting all Fastify headers on the raw response before passing control to Next.js or a custom Next.js route handler.
However, it doesn't appear to be possible to solve this problem for headers set via `reply` in a custom Next.js route handler itself if the custom handler calls Next.js's `app.render()` directly. In that scenario, the custom handler will still need to ensure that …
> Preserve Fastify response headers set by plugins and hooks

- .taprc
- README.md
- index.d.ts
- index.js
- package-lock.json
- package.json
- test.js
- types.test.ts
also 100% test coverage and other minor fixes
> feat: under-pressure integration

- README.md
I try to implement next-auth in a project where I use fastify-next. For that reason, POST routes to the internal API route are needed. I was not aware that the HTTP methods need to be specified - until I checked the source. So I thought a doc update might be helpful.
> Moar docs updates

- package-lock.json
- package.json
Update the range to be inclusive for next@10. The new Next.js major does not seem to introduce any other requirements for this module. Happy to change the solution according to maintainer preferences.
This will ensure installs with `npm@7` while using `next@10` won't require the `--legacy-peer-deps` flag.
~- [ ] tests and/or benchmarks are included~
~- [ ] documentation is changed or added~
> Update next peerDepedency range >=9.3.1

- .github/workflows/ci.yml
Try out the new version of the action
> chore: update dependabot merge action to @next

- README.md
rename `renderNext` to `nextRender`.
> docs(readme): nextRender typo

- README.md
- index.d.ts
- index.js
- test.js
- types.test.ts
1. Add `noServeAssets` option for disable in-box next assets serving.
2. Fix in-box assets serving when used [basePath](https://nextjs.org/docs/api-reference/next.config.js/basepath).
3. Improved plugin options type definition.
4. Fix options reading (before forwarding to Next, remove `noServeAssets` and `underPressure ` when they are `false`).
I use `fastify-nextjs` for split huge monolithic high-load legacy project with React and Rails. 
I use [basePath](https://nextjs.org/docs/api-reference/next.config.js/basepath) for transition-time (time for moving pages/routes to new Next-app with same code-base) and SEO-comparison tests (compare content for legacy versions of pages with next-pages). 
And in same time i use build without `basePath`, for override transited pages on stages and prod. …
> `noServeAssets` option for disable in-box next assets serving.

- index.d.ts
- types.test.ts
I use Next.js `app` argument wider than just method `getRequestHandler`, that repeats on both `DevServer` and `NextServer`. But it different objects, and now `DevServer` is mistake. 
For access for real `DevServer` (It would be more correct to say `Server` — ancestor of `DevServer`, which only in development mode) you can use `app.server.*`.
> Fix TypeScript declaration of `app` argument in callback

- test.js
Fixes tests around Next generated assets as they are now 5 instead of 4 per each page. Removes the dependency on the assumption about how many assets are generated.
Note: it merges into the dependabot bump branch.
> fix: next 10.1.3

- .github/workflows/ci.yml
- package-lock.json
- package.json
- tsconfig.json
We have Next 12 now (https://github.com/vercel/next.js/releases/tag/v12.0.0), it's better to add them in peerDependencies so we don't need to use --force when installing
> Add Next 12 in peerDependencies

- README.md
- index.js
- pages/_error.jsx
- test.js
Closes #435 
Proxy to Next.js `app.renderError`.
The source code for `app.renderError` at time of writing can be found here:
- [`app.renderError`](https://github.com/vercel/next.js/blob/dda0afd3a45a50cbcb418903f7a0ab56eae51b33/packages/next/server/base-server.ts#L2336) (public)
- [`app.renderErrorToResponse`](https://github.com/vercel/next.js/blob/dda0afd3a45a50cbcb418903f7a0ab56eae51b33/packages/next/server/base-server.ts#L2369) (private)
This method will render an appropriate error page based on the **response status code** - the pathname does not affect the page rendering.
The page that will be rendered by this method can include:
- `/pages/_error.js`
- `/pages/404.js`
- `/pages/500.js`
> Decorate reply with nextRenderError

- index.js
- package-lock.json
- package.json
Hello.
This PR aims to :
- remove 2 statements that are not needed since the release of `fastify@3.22.1`
- unlock the upgrade of `fastify` dependency by our GitHub action workflow
- upgrade package dependencies (fix https://github.com/fastify/fastify-nextjs/issues/470)
For reference: 
- the PR that introduced the behavior: https://github.com/fastify/fastify/pull/2546
- the PR that fixed the behavior: https://github.com/fastify/fastify/pull/3375
> fix (coverage): remove statements not needed since `fastify@3.22.1`

- README.md
Hi,
I added the Known Errors Section as discussed here: https://github.com/fastify/fastify-nextjs/issues/464
> Doc: add known errors section for the plugin timeout error

- README.md
- index.d.ts
- index.js
- package-lock.json
- package.json
- test.js
Fixes https://github.com/fastify/fastify-nextjs/issues/549.
- [ x commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
> fix: update under-pressure -> @fastify/under-pressure

- index.js
- package-lock.json
- package.json
**fastify-nextjs** is not working for **next@13.4** because it breaks when trying to access
```javascript
const basePath = app.server.nextConfig.basePath || ''
```
with ```Cannot read properties of undefined (reading 'nextConfig')```
To recreate this issue, update next to the latest version and run the tests, all fail with this error.
NextServer provides the `getServer()` method which returns a promise that returns the server. I changed it to use this function instead of ```app.server``` and fortunately this is also compatible with 13.0.0, the version the tests were previously running on.
Tests are now passing with 13.0 and 13.4
> fix: undefined app.server for next 13.4

- package.json
Reverts fastify/fastify-nextjs#862
If we remove this, then CI will pass and also dependabot PRs should run through.
> Revert "chore(package): explicitly declare js module type"

- .github/workflows/ci.yml
- .taprc
- index.js
- package-lock.json
- package.json
- test/index.test.js
- types/index.d.ts
Ref: https://github.com/fastify/fastify/issues/5116
⚠️ There is one small issue with this one, and it's the NextJS dependency. Upgrading it to v14.x will ignore the `basePath` option. Even thought the `basePath` is still present in their config docs and typings it does not work. I am unsure if this [doc](https://nextjs.org/docs/app/building-your-application/upgrading/app-router-migration) saying that it was removed might have something to do with this issue. 
I am open to discuss what would be the best way to fix this one.
CC @simoneb
> Update for Fastify v5

- .github/workflows/ci.yml
See https://github.com/fastify/fastify/pull/5577. This is a batch PR, so may have some issues. Please review changes.
> ci(.github): use latest node version

- .github/workflows/ci.yml
This PR is created by a script. Please check the changes prior to merging.
This PR adds permissions to the workflow and job level, making the workflows read-only by default, and allowing write access only at the job level via granular permissions. This is regularly flagged by CodeQL, Step Security, [OSSF](https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions), and other security tools.
This change also allows the org to go read-only everywhere, see https://github.com/fastify/avvio/pull/308#issuecomment-2765300174
> ci: set workflow permissions to read-only by default
