fastify/fastify-nextjs

index.js
package.json

Needed to be compliant with the latest version of Fastify.
Closes #2 and #3

Fix schema

---

package.json

fix(package): update next to version 3.0.3

---

index.js
package.json
test.js

- updates to fastify@0.39 #18 
- adds `name` property to plugin-meta. see: https://github.com/fastify/fastify-plugin/issues/17#issuecomment-357446781

Updates fastify, plugin-meta

---

README.md
index.js
package.json
test.js

As titled.
Related: #28 
cc @binarykitchen

Update to support the latest version of fastify

---

.gitignore
.travis.yml
README.md
example.js
index.js
package.json
test.js

May related to #32 which I can't reproduce.

Updates dependencies

---

README.md
package.json

Add `next` to peerDependencies

---

index.js
test.js

**Description**
This is a PR in reference to #52 see for further details.

ISSUE-52 PR (Object assignment)

---

package.json

chore(package): update @types/node to version 12.12.7

---

README.md

Fix small typo's

---

index.js
test.js

bug #47 reappeared, since the changes made in #46 were lost somewhere.

Tell fastify a response was sent (redo #46)

---

index.js
test.js

Object.assign example: https://runkit.com/alekzonder/object-assign

Fix dev option default value processing (bug #102)

---

.dependabot/config.yml
.github/dependabot.yml
.github/workflows/ci.yml

- Upgraded dependabot config to v2
- Added workflow to auto merge dependabot PRs once tests pass.

chore: dependabot auto merge

---

.github/workflows/ci.yml

chore: use fastify/github-action-merge-dependabot

---

README.md
index.d.ts
index.js
test.js

I'm attempting to migrate our custom Next server from express to fastify, and hit a snag with setting up our error page.
Exposing `nextRender` seems like a nicely flexible way of adding the capability

feat: add reply.nextRender to manually render next pages from other handlers

---

.github/workflows/ci.yml
README.md

chore: ci updates and style change 

---

index.d.ts
index.test-d.ts

Add nextRenderError to types definition

---

package-lock.json
package.json

Make tsd a dev dep

---

README.md

I initially thought this library was the way to replace the server NextJS uses internally with Fastify instead (as a [Custom Server](https://nextjs.org/docs/advanced-features/custom-server)).

Doc: Add clarification on what fastify-nextjs is for.

---

index.js

Hello.
This PR aims to :
- avoid manipulations of the plugin options by using object destructuring assignments

refactor: avoid options mutations by using object destructuring

---

README.md
index.d.ts
index.js
package-lock.json
package.json
test.js

Restore fastify v3 compat

---

index.d.ts
index.js
package-lock.json
package.json

resolves #557 
resolves #549 
closes #588 
closes #563 

upgrade to fastify 4 and latest under pressure

---

package-lock.json
package.json

ref https://github.com/fastify/under-pressure/issues/184

fix: update under-pressure

---

package-lock.json
package.json

remove old major next versions as peerDependencies

---

README.md
index.js
types/index.test-d.ts

Fixes #609.
Not sure if anything else is needed?

fix: use `reply.hijack()` over `reply.sent`

---

package.json

Used in tests but not explicitly defined as dependency:
https://github.com/fastify/fastify-nextjs/blob/90d92ace42ae9a76e1861796a05818bb7f9fa876/test/index.test.js#L7

build(deps-dev): add pino

---

.github/workflows/ci.yml
package-lock.json
package.json

https://nextjs.org/blog/next-13

feat: upgrade to Next 13

---

.github/workflows/ci.yml

drop node 14 support

---

index.js

See https://github.com/fastify/fastify-static/pull/407

perf: use `node:` prefix to bypass require.cache call for builtins

---

pages/custom_prop_page.jsx

my citgm workflow shows for some reason linter errors. This should fix them.

fix linting error

---

README.md

Proposal:
- Updated the code snippet related to the options of the `listen()` method ( see screenshot )

docs(readme): update snippet code

---

README.md

Target the master branch, or else the badge will reflect any runs of the CI workflow, including any failing ones on PRs.

docs(readme): update ci badge target
